/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
@RestResource(urlMapping='/package-version/')
global class HubSpotVersionResource {
    global HubSpotVersionResource() {

    }
    @HttpGet
    global static String getInstalledPackageVersion() {
        return null;
    }
}
