/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class FavoritesManagerController {
    global FavoritesManagerController() {

    }
    @RemoteAction
    global static String loadFavoriteModel(String quoteJSON) {
        return null;
    }
    @RemoteAction
    global static String loadUsersToShare(String searchCriteria) {
        return null;
    }
    @RemoteAction
    global static String removeFromFavorites(String quoteJSON, List<Id> favoriteIds) {
        return null;
    }
    @RemoteAction
    global static String shareFavoritesWithUsersAndGroups(String quoteJSON, List<Id> favoriteIds, List<Id> groupIds, List<Id> userIds) {
        return null;
    }
}
