/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class InstallProcessor implements SBQQ.InstallExecutor, System.InstallHandler {
    global static void emailOnAbort(String msg) {

    }
    global static void emailOnFail(String msg, Boolean isInstall) {

    }
    global static void emailOnFailedJob(String jobName, AsyncApexJob apexJob, Map<Id,List<String>> errorMap, Boolean isInstall) {

    }
    global static List<Id> execute() {
        return null;
    }
}
