/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class QuoteDocumentController {
    global static void emailMeProposal(String quoteId, String templateId, String documentName, String outputFormat, List<String> documentIds) {

    }
    global static void emailMeProposal(String language, String quoteId, String templateId, String documentName, String outputFormat, List<String> documentIds) {

    }
    @RemoteAction
    global static void emailMeProposal(String language, String quoteId, String templateId, String documentName, String outputFormat, String paperSize, List<String> documentIds) {

    }
    global static String generateDocument(String language, String quoteId, String templateId, String documentName, String outputFormat, List<String> documentIds) {
        return null;
    }
    @RemoteAction
    global static String generateDocument(String language, String quoteId, String templateId, String documentName, String outputFormat, String paperSize, List<String> documentIds) {
        return null;
    }
    global static List<String> generateDocuments(String quoteId, String templateId, String documentName, String outputFormat, List<String> documentIds) {
        return null;
    }
    global static List<String> generateDocuments(String language, String quoteId, String templateId, String documentName, String outputFormat, List<String> documentIds) {
        return null;
    }
    global static String generateProposal(String quoteId, String templateId, String documentName, String outputFormat, List<String> documentIds, Boolean isMobile) {
        return null;
    }
    global static String generateProposal(String language, String quoteId, String templateId, String documentName, String outputFormat, List<String> documentIds, Boolean isMobile) {
        return null;
    }
    @RemoteAction
    global static String generateProposal(String language, String quoteId, String templateId, String documentName, String outputFormat, String paperSize, List<String> documentIds, Boolean isMobile) {
        return null;
    }
    @RemoteAction
    global static String listRelatedContent(String quoteId, String templateId) {
        return null;
    }
    global static String loadDocumentModel(String quoteId) {
        return null;
    }
    @RemoteAction
    global static String loadModel(String quoteId, String action) {
        return null;
    }
    global static String saveAndEmailProposal(String quoteId, String templateId, String documentName, String outputFormat, List<String> documentIds) {
        return null;
    }
    global static String saveAndEmailProposal(String language, String quoteId, String templateId, String documentName, String outputFormat, List<String> documentIds) {
        return null;
    }
    @RemoteAction
    global static String saveAndEmailProposal(String language, String quoteId, String templateId, String documentName, String outputFormat, String paperSize, List<String> documentIds) {
        return null;
    }
    global static String saveAndSendProposalForESignature(String quoteId, String templateId, String documentName, String outputFormat, List<String> documentIds) {
        return null;
    }
    global static String saveAndSendProposalForESignature(String language, String quoteId, String templateId, String documentName, String outputFormat, List<String> documentIds) {
        return null;
    }
    @RemoteAction
    global static String saveAndSendProposalForESignature(String language, String quoteId, String templateId, String documentName, String outputFormat, String paperSize, List<String> documentIds) {
        return null;
    }
    global static String saveProposal(String quoteId, String templateId, String documentName, String outputFormat, List<String> documentIds) {
        return null;
    }
    global static String saveProposal(String language, String quoteId, String templateId, String documentName, String outputFormat, List<String> documentIds) {
        return null;
    }
    @RemoteAction
    global static String saveProposal(String language, String quoteId, String templateId, String documentName, String outputFormat, String paperSize, List<String> documentIds) {
        return null;
    }
}
