/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global interface RuleListener {
    void onAfterRuleEvaluated(SObject param0, SObject param1, Boolean param2);
    void onAfterRuleExecuted(SObject param0, SObject param1);
    void onBeforeRuleEvaluated(SObject param0, SObject param1);
    void onBeforeRuleExecuted(SObject param0, SObject param1);
}
