/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class SubscriptionLookupController {
    global SubscriptionLookupController() {

    }
    @RemoteAction
    global static String loadSearchModel(String quoteJSON, String customActionId) {
        return null;
    }
    @RemoteAction
    global static String search(String quoteJSON, String filterValuesJSON, String customActionId, Integer resultLimit) {
        return null;
    }
}
