/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
@RestResource(urlMapping='/RecordJobService/*')
global class RecordJobService {
    global RecordJobService() {

    }
    @HttpPost
    global static void createRecordJob(String jobId, String jobType) {

    }
    global static void createRecordJobWithResult(String jobId, String jobType, String result) {

    }
    @HttpPatch
    global static void createRecordJobWithResult(String jobId, String jobType, Boolean isFailed, String result) {

    }
    @HttpPut
    global static void uploadResult(String jobId, String jobType, String result) {

    }
}
