/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class ElectronicDocumentProcessor implements Database.Batchable<SBQQ__QuoteDocument__c> {
    global ElectronicDocumentProcessor() {

    }
    global void execute(Database.BatchableContext bc, List<SBQQ__QuoteDocument__c> documents) {

    }
    global void finish(Database.BatchableContext bc) {

    }
    global List<SBQQ__QuoteDocument__c> start(Database.BatchableContext bc) {
        return null;
    }
}
