/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global interface QuoteCalculatorPlugin {
    void onAfterCalculate(SObject param0, List<SObject> param1);
    void onAfterPriceRules(SObject param0, List<SObject> param1);
    void onBeforeCalculate(SObject param0, List<SObject> param1);
    void onBeforePriceRules(SObject param0, List<SObject> param1);
    void onInit(List<SObject> param0);
}
