/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global interface RuleActionListener extends SBQQ.RuleListener {
    void onAfterRuleActionExecuted(SObject param0, SObject param1, Schema.SObjectField param2);
    void onBeforeRuleActionExecuted(SObject param0, SObject param1, Schema.SObjectField param2);
}
