/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global virtual class DefaultElectronicSignaturePlugin implements SBQQ.ElectronicSignaturePlugin, SBQQ.ElectronicSignaturePlugin2, SBQQ.ElectronicSignaturePlugin3 {
    global DefaultElectronicSignaturePlugin() {

    }
    global virtual String getSendButtonLabel() {
        return null;
    }
    global virtual Boolean isSendButtonEnabled() {
        return null;
    }
    global virtual void revoke(List<SBQQ__QuoteDocument__c> documents) {

    }
    global virtual String sendWithRedirect(List<SBQQ__QuoteDocument__c> documents) {
        return null;
    }
    global virtual void send(List<SBQQ__QuoteDocument__c> documents) {

    }
    global virtual void updateStatus(List<SBQQ__QuoteDocument__c> documents) {

    }
}
