/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
@RestResource(urlMapping='/v1/quotes/*')
global class QuoteRestEndpoint {
    global QuoteRestEndpoint() {

    }
    @HttpGet
    global static void doGet() {

    }
    @HttpPost
    global static void doPost() {

    }
    global static void doPostV1(System.RestRequest req) {

    }
    @HttpPut
    global static void doPut() {

    }
    global static void doPutV1(System.RestRequest req) {

    }
}
