/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class RenewalAPI {
    global RenewalAPI() {

    }
    global static void forecastContracts(List<SObject> contracts, Id masterContractId) {

    }
    global static Boolean hasPassedEvergreenValidationChecks(SObject oldContract, SObject newContract) {
        return null;
    }
    global static void processContracts(List<SObject> forecastContracts, List<SObject> renewedContracts, List<SObject> masterContracts) {

    }
    global static void renewContracts(List<SObject> contracts, Id masterContractId) {

    }
    global static void updateRenewalOpportunities(Set<Id> contractIds) {

    }
}
