/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class ContractAPI {
    global ContractAPI() {

    }
    global static List<SObject> loadContracts(Set<Id> contractIds) {
        return null;
    }
    global static void processSubscriptionTriggerAfterUpdate(SObject recordObject) {

    }
    global static void processTriggerAfter() {

    }
    global static void renewContracts(List<SObject> contracts, Id masterContractId) {

    }
}
