/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class TriggerControl {
    global TriggerControl() {

    }
    global Boolean alreadyRun(SObject record) {
        return null;
    }
    global Boolean alreadyRun(List<SObject> records) {
        return null;
    }
    global void block() {

    }
    global static void disable() {

    }
    global static void enable() {

    }
    global static SBQQ.TriggerControl getInstance() {
        return null;
    }
    global Boolean isDisabled() {
        return null;
    }
    global static Boolean isEnabled() {
        return null;
    }
    global void reset() {

    }
    global void setDisabled() {

    }
    global Boolean shouldRun(SObject record) {
        return null;
    }
global class CrossPackageDisableHook {
    global CrossPackageDisableHook() {

    }
}
global class CrossPackageEnableHook {
    global CrossPackageEnableHook() {

    }
}
}
