/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global interface PageSecurityPlugin2 extends SBQQ.PageSecurityPlugin {
    Boolean isFieldEditable(String param0, Schema.SObjectField param1, SObject param2);
    Boolean isFieldVisible(String param0, Schema.SObjectField param1, SObject param2);
}
