/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
@RestResource(urlMapping='/LookupCallout/*')
global class LookupTableCallout implements SBQQ.ServiceLoader {
    global LookupTableCallout() {

    }
    @HttpGet
    global static String callGet() {
        return null;
    }
    @HttpPost
    global static Map<String,List<SObject>> queryRows() {
        return null;
    }
global class TableMap {
}
}
