/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class AmendContractController {
    global Map<Id,SBQQ.AmendContractController.AggregatedSub> aggregatedSubs {
        get;
    }
    global String contractNumber {
        get;
    }
    global String displayedSubscriptionsMsg {
        get;
    }
    global Id jobId {
        get;
    }
    global AmendContractController(ApexPages.StandardController stdController) {

    }
    global System.PageReference onAmend() {
        return null;
    }
    global System.PageReference returnToContract() {
        return null;
    }
}
