/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class RefreshQuotePricesController {
    webService static String onRefresh(String quoteId) {
        return null;
    }
    webService static String onRefreshList(List<String> quoteIdList) {
        return null;
    }
}
