/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global virtual class DefaultPageSecurityPlugin implements SBQQ.PageSecurityPlugin, SBQQ.PageSecurityPlugin2 {
    global DefaultPageSecurityPlugin() {

    }
    global virtual Boolean isFieldEditable(String pageName, Schema.SObjectField field) {
        return null;
    }
    global virtual Boolean isFieldEditable(String pageName, Schema.SObjectField field, SObject recordz) {
        return null;
    }
    global virtual Boolean isFieldVisible(String pageName, Schema.SObjectField field) {
        return null;
    }
    global virtual Boolean isFieldVisible(String pageName, Schema.SObjectField field, SObject record) {
        return null;
    }
}
