/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class QuotePriceRefreshBatch implements Database.AllowsCallouts, Database.Batchable<SObject>, Database.Stateful {
    global QuotePriceRefreshBatch(Schema.SObjectType quoteType, Set<Id> quoteIds) {

    }
    global void execute(Database.BatchableContext ctx, List<SObject> scope) {

    }
    global void finish(Database.BatchableContext ctx) {

    }
    global Database.QueryLocator start(Database.BatchableContext ctx) {
        return null;
    }
}
