/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class AssetLookupController {
    global static String amendAssets(List<Id> selectedAssetIds, Id accountId, Boolean isAssetBased) {
        return null;
    }
    @RemoteAction
    global static String amendAssets(List<Id> selectedAssetIds, Id accountOrOppId, Boolean isAssetBased, Id pricebookId) {
        return null;
    }
    @RemoteAction
    global static String loadPricebooks() {
        return null;
    }
    @RemoteAction
    global static String loadSearchModel(String quoteJSON, String customActionId) {
        return null;
    }
    @RemoteAction
    global static String onloadSearchModel(String accountId, Boolean isAmend) {
        return null;
    }
    @RemoteAction
    global static String renewAssetsByMasterId(List<Id> selectedAssetIds, Id accountId, Boolean isAssetBased, Id masterAssetId) {
        return null;
    }
    @RemoteAction
    global static String renewAssets(List<Id> selectedAssetIds, Id accountId, Boolean isAssetBased) {
        return null;
    }
    @RemoteAction
    global static String search(String quoteJSON, String filterValuesJSON, String customActionId, Integer resultLimit) {
        return null;
    }
    @RemoteAction
    global static String searchByAssetBased(String accountId, Boolean isAmend, String filterValuesJSON) {
        return null;
    }
}
