/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class RenewContractsController {
    global Boolean isEvergreen {
        get;
        set;
    }
    global Id jobId {
        get;
    }
    global String masterContractId {
        get;
        set;
    }
    global List<SObject> selectedServiceContracts {
        get;
    }
    global RenewContractsController(ApexPages.StandardSetController setController) {

    }
    global void displayCheckerErrorMessage() {

    }
    global void displayIndividualFailureMessages() {

    }
    global String getRenewedContractIdsJson() {
        return null;
    }
    global System.PageReference onCancel() {
        return null;
    }
    global System.PageReference onInit() {
        return null;
    }
    global System.PageReference onRenew() {
        return null;
    }
}
